//
//  STKIncoming.h
//  Strik
//
//  Created by Nils on Aug 1, 2013.
//  Copyright (c) 2013 Indev. All rights reserved.
//

typedef NS_ENUM(int8_t, STKIncomingOpcode)
{
	VERSIONCHECK,
	SERVER_CRYPTO,
	SESSION_INFO,
	CREDENTIALS,
	PLAYER_INFO,
	PLAYER_UNKNOWN,
	LEVELS,
	CURRENCY_BALANCE,
	ITEM_TYPES,
	ITEMS,
	ITEMS_ADDED,
	FACEBOOK_STATUS,
	FACEBOOK_FRIEND_PLAYERS,
	FACEBOOK_FRIENDS_UPDATE,
	NAME_CHANGED,
	NAME_REJECTED,
	AVATAR_CHANGED,
	QUEUE_ENTERED,
	QUEUE_EXITED,
	CHALLENGE,
	CHALLENGE_OK,
	CHALLENGE_FAILED,
	CHALLENGE_REDIRECT,
	CHALLENGE_LOCALE_MISMATCH,
	CHALLENGE_DECLINED,
	ANNOUNCE_MATCH,
	MATCH_STARTED,
	MATCH_ENDED,
	BOARD_INIT,
	BOARD_UPDATE,
	WORD_FOUND,
	WORD_NOT_FOUND,
	EXPERIENCE_ADDED,
	ALERT,
	SERVER_SHUTTING_DOWN,
	SERVER_REDIRECT,
	ACTIVITY_STREAM,
	NEWS,
	SHOP_PAGE,
	IN_APP_PURCHASE_PRODUCTS,
	IN_APP_PURCHASE_DELIVERED
};